# Generated by Django 4.0 on 2021-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_url', models.URLField()),
                ('theme_name', models.CharField(max_length=255)),
            ],
        ),
    ]
