# Generated by Django 4.0 on 2021-12-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thememodel',
            name='theme_name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
