# Generated by Django 4.0 on 2021-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_api', '0002_alter_thememodel_theme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thememodel',
            name='theme_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
